#!/usr/bin/perl
use strict;
use warnings;
use Socket;

socket (SERVEUR, PF_INET, SOCK_STREAM, getprotobyname('tcp'));
setsockopt (SERVEUR, SOL_SOCKET, SO_REUSEADDR, 1);
my $mon_adresse = sockaddr_in ("7777", INADDR_ANY);

bind(SERVEUR, $mon_adresse) || die ("bind");
listen (SERVEUR, SOMAXCONN) || die ("listen");
accept (CLIENT, SERVEUR) || die ("accept");

select(CLIENT);
$|=1;
select(STDOUT);

while (<CLIENT>){
	print CLIENT $_;
}

close (CLIENT);
close (SERVEUR);
