#!/usr/bin/perl
use strict;
use warnings;
use Socket;

socket (SERVEUR, PF_INET, SOCK_STREAM, getprotobyname('tcp'));
setsockopt (SERVEUR, SOL_SOCKET, SO_REUSEADDR, 1);
my $mon_adresse = sockaddr_in ("3000", INADDR_ANY);

bind(SERVEUR, $mon_adresse) || die ("bind");
listen (SERVEUR, SOMAXCONN) || die ("listen");
accept (CLIENT, SERVEUR) || die ("accept");
select (CLIENT);
for (my $i = 0; $i < $ARGV[0] ; $i++) {
	print "bonjour\n";
}
close (CLIENT);
close (SERVEUR);
